myproject/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('task.urls', namespace='task')),
]

task/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # home
    url(r'^$', views.index, name='topics'),
    url(r'^topics/$', views.topics, name='topics'),
    url(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),
    url(r'^new_topic/$', views.new_topic, name='new_topic'),
    url(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),
    url(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry,name='edit_entry'),
]

task/models.py
from django.db import models


class Topic(models.Model):
    '''user thhem'''
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    ''':returns model to string'''
    def __str__(self):
        return self.text


class Entry(models.Model):
    """user information them"""
    topic = models.ForeignKey(Topic)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

        def __str__(self):
            """:returns model to string"""
            return self.text[:50] + "..."

# Create your models here.

task/forms.py
from django import forms
from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

task/views.py
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse

from django.shortcuts import render
from .models import Topic, Entry
from .forms import TopicForm, EntryForm

def index(request):
    """home page app task"""
    # return render(request, 'task/index.html')
    topics = Topic.objects.order_by('date_added')
    context = {'topics': topics}
    return render(request, 'task/topics.html', context)

def topics(request):
    topics = Topic.objects.order_by('date_added')
    context = {'topics': topics}
    return render(request, 'task/topics.html', context)


def topic(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'task/topic.html', context)


def new_topic(request):
    """new theme"""
    if request.method != 'POST':
    # no send data empty form
        form = TopicForm()
    else:
    # send POST; data hendler.
        form = TopicForm(request.POST)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('task:topics'))

    context = {'form': form}
    return render(request, 'task/new_topic.html', context)


def new_entry(request, topic_id):
    """add new write."""
    topic = Topic.objects.get(id=topic_id)
    if request.method != 'POST':
    # no send data empty form
        form = EntryForm()
    else:
    # send POST; data hendler.
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('task:topic',args=[topic_id]))
    context = {'topic': topic, 'form': form}
    return render(request, 'task/new_entry.html', context)


def edit_entry(request, entry_id):
    """edit."""

    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic

    if request.method != 'POST':
        # form current data.
        form = EntryForm(instance=entry)
    else:
        # send POST; data hendler.
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('task:topic', args=[topic.id]))
    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'task/edit_entry.html', context)

# Create your views here.

task/templates/task/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
    {% load bootstrap3 %}
    <script src="{% bootstrap_jquery_url %}"></script>
    {% bootstrap_javascript %}
    {% bootstrap_css %}

    <style>
        .content{
            margin:0 auto;
            width: 600px;
        }
    </style>

</head>

<body>
<div class="content">

    <h1> тестовое задание </h1>

    {% block content %}{% endblock content %}

</div>
</body>
</html>

task/templates/task/edit_entry.html
{% extends "task/base.html" %}
{% block content %}
    <p><a href="{% url 'task:topic' topic.id %}">{{ topic.text }}</a></p>
    <p>Редактировать запись:</p>
    <form action="{% url 'task:edit_entry' entry.id %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Сохранить изменения</button>
    </form>
{% endblock content %}

task/templates/task/index.html
{% extends "task/base.html" %}
{% block content %}
<p>Темы</p>
<ul class="list-group">
    {% for topic in topics %}
        <li class="list-group-item">
            <a href="{% url 'task:topic' topic.id %}">{{ topic }}</a>
        </li>
    {% empty %}
        <li>Темы еще не добавлены. еще не добавлены.</li>

    {% endfor %}
</ul>
    <a href="{% url 'task:new_topic' %}">Добавить новую тему:</a>
{% endblock content %}

task/templates/task/new_entry.html
{% extends "task/base.html" %}

{% block content %}
    <p><a href="{% url 'task:topic' topic.id %}">{{ topic.text }}</a></p>
    <p>Добавление новой записи:</p>
    <form action="{% url 'task:new_entry' topic.id %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button name='submit'>Добавить запись</button>
    </form>
{% endblock content %}

task/templates/task/new_topic.html
{% extends "task/base.html" %}
{% block content %}
    <p>Добавить тему:</p>
    <form action="{% url 'task:new_topic' %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Добавить тему</button>
    </form>
{% endblock content %}

task/templates/task/topic.html
{% extends 'task/base.html' %}
{% block content %}
    <div>
        <a href="{% url 'task:topics' %}">Темы</a>

        <a href="{% url 'task:new_entry' topic.id %}">Добавить новую запись</a>
    </div>
    <p>Тема: {{ topic.text }}</p>
    <p>Записи:</p>

    <script type="javascript">
        function red(id) {
            var elem = document.getElementById(id);
            elem.style.color = "red";
        }
    </script>
    
    <ul class="list-group">
        {% for entry in entries %}
            <li  class="card-body" id = "{{ entry.id }}">
                <h3 class="card-title">{{ entry.date_added|date:'M d, Y H:i' }}</h3>
                <p class="card-title">{{ entry.text|linebreaks }}</p>
                <a href="{% url 'task:edit_entry' entry.id %}" class="btn btn-outline-primary"
                      role="button" aria-pressed="true">Править запись</a>
                <button type="button" class="btn btn-danger"
                        onclick="document.getElementById({{ entry.id }}).style.color = 'red'">Покрасить в красный</button>
            </li>
        {% empty %}
            <li>
                Записей по этой теме пока нет.
            </li>
        {% endfor %}
    </ul>
{% endblock content %}

task/templates/task/topics.html
{% extends "task/base.html" %}
{% block content %}
<p  class="lead">Темы</p>
<ul class="list-group">
    {% for topic in topics %}
        <li class="list-group-item">
            <a href="{% url 'task:topic' topic.id %}">{{ topic.text }}</a>
        </li>
    {% empty %}
        <li>Темы еще не добавлены.</li>

    {% endfor %}
</ul>
    <a href="{% url 'task:new_topic' %}">Добавление новой темы:</a>
{% endblock content %}